name: Gradle Verification

on: [ push ]

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  ui-tests:
    needs: [ unit-tests ]
    uses: ./.github/workflows/ui-tests.yml
    secrets: inherit
