name: Gradle Verification

on:
  - push
  - pull_request

jobs:
  gradle-verification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create dummy local.properties
        run: echo "appToken=\"ARBITRARY\"" > local.properties

      - run: ./gradlew build

      - run: ./gradlew test
