name: Gradle Verification

on:
  push:
  pull_request:

env:
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis_playstore
  API_LEVEL: 34
  BUILD_TOOLS_VERSION: 34.0.2
  ANDROID_SDK_PACKAGES: system-images;android-34;google_apis_playstore;x86_64 platforms;android-34 build-tools;33.0.2 platform-tools emulator
  EMULATOR_TIMEOUT: 350
  EMULATOR_NAME: api34

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create dummy local.properties
        run: echo "appToken=\"ARBITRARY\"" > local.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

  instrumented-tests:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Add avdmanager and sdkmanager to system PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH

      - name: Install Sdk
        run: |
          yes Y | sdkmanager --licenses
          sdkmanager --install ${ANDROID_SDK_PACKAGES}

      - name: Build emulator
        run: |
          echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --abi "${ANDROID_TARGET}/${ANDROID_ARCH}" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"

      - name: Launch emulator
        run: emulator -avd $EMULATOR_NAME -no-window -no-audio -gpu swiftshader_indirect -camera-back none -camera-front none -selinux permissive -metrics-collection &

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          booted=false
          while [ "$booted" == "false" ]; do
            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
            if [ "$boot_completed" == "1" ]; then
              booted=true
            else
              sleep 5
            fi
          done

      - name: Disable animations
        run: |
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Add Dummy local.properties
        run: echo "appToken=\"ARBITRARY\"" > local.properties

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest