name: Gradle Verification

on: [ push ]

jobs:
  unit-tests:
    uses: ./unit-tests.yml

#  instrumented-tests:
#    runs-on: macos-13
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#          cache: 'gradle'
#
#      - name: Add Dummy local.properties
#        run: echo "appToken=\"ARBITRARY\"" > local.properties
#
#      - name: Run connected tests
#        uses: ReactiveCircus/android-emulator-runner@v2
#        with:
#          api-level: 30
#          target: google_apis
#          arch: x86_64
#          script: ./gradlew connectedCoreDebugAndroidTest
#          ram-size: 4096M
#          heap-size: 2048M
#          disk-size: 4096M
#          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#          disable-animations: true