name: Unit Tests

on: [ workflow_call ]

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create dummy local.properties
        run: echo "appToken=\"ARBITRARY\"" > local.properties

      - name: Run Unit Tests
        run: ./gradlew test
